import os
import json
import logging
from database import db
from analyzer import analyze_site, generate_ai_audit, calculate_revenue_loss
from jinja2 import Template

# Config
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("diamond_generator")

DIAMOND_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EXCLUSIVE REVENUE AUDIT: {{ business_name }}</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;700;900&display=swap" rel="stylesheet">
    <style>
        :root { --accent: #ff4d94; --bg: #0a0a0c; --card: #141417; --t1: #ffffff; --t2: #a0a0ab; }
        body { font-family: 'Outfit', sans-serif; background: var(--bg); color: var(--t1); margin: 0; padding: 40px 20px; line-height: 1.6; }
        .container { max-width: 900px; margin: auto; }
        .header { text-align: center; margin-bottom: 60px; }
        h1 { font-size: 3.5rem; font-weight: 900; text-transform: uppercase; margin: 0; letter-spacing: -2px; line-height: 1; }
        .highlight { color: var(--accent); }
        .leak-badge { font-size: 5rem; font-weight: 900; color: var(--accent); margin: 20px 0; border: 4px solid var(--accent); padding: 20px; display: inline-block; border-radius: 20px; transform: rotate(-2deg); box-shadow: 0 0 40px rgba(255, 77, 148, 0.3); }
        .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-top: 40px; }
        .card { background: var(--card); padding: 40px; border-radius: 24px; border: 1px solid rgba(255,255,255,0.05); }
        .bullet { margin-bottom: 24px; font-size: 1.2rem; color: var(--t1); border-left: 3px solid var(--accent); padding-left: 20px; }
        .label { font-size: 0.75rem; color: var(--t2); text-transform: uppercase; letter-spacing: 2px; font-weight: 700; margin-bottom: 8px; }
        .cta-box { text-align: center; margin-top: 60px; background: linear-gradient(135deg, #ff4d94 0%, #7000ff 100%); padding: 60px; border-radius: 30px; }
        .cta-btn { background: white; color: black; padding: 20px 50px; border-radius: 50px; text-decoration: none; font-weight: 900; font-size: 1.2rem; display: inline-block; transition: transform 0.3s; }
        .cta-btn:hover { transform: scale(1.05); }
        .footer { text-align: center; margin-top: 40px; opacity: 0.3; font-size: 0.7rem; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="label">Confidential Report Prepared for</div>
            <h1>{{ business_name }}</h1>
            <p style="color:var(--t2); font-size: 1.2rem;">Our proprietary algorithm has detected a significant annual revenue leak.</p>
            <div class="leak-badge">${{ annual_leakage }}/YR</div>
            <div class="label">Estimated Revenue Recovery Potential</div>
        </div>

        <div class="card">
            <div class="label">Executive Summary & Technical Failures</div>
            <div style="font-size: 1.1rem; color: var(--t2); margin-bottom: 30px;">
                I've performed a deep audit of {{ domain if domain else business_name }}. Your digital infrastructure is currently repelling high-value prospects. 
                Based on your niche LTV, the following failures are bleeding capital:
            </div>
            {% for bullet in ai_bullets %}
                <div class="bullet">{{ bullet }}</div>
            {% endfor %}
        </div>

        <div class="grid">
            <div class="card">
                <div class="label">Mobile Integrity</div>
                <div style="font-size: 2rem; font-weight: 900; color: {{ 'var(--accent)' if not mobile_friendly else '#00ff88' }}">{{ 'FAIL' if not mobile_friendly else 'PASS' }}</div>
                <p>Mobile conversion is the #1 driver of new client acquisition in your niche.</p>
            </div>
            <div class="card">
                <div class="label">Speed Rating</div>
                <div style="font-size: 2rem; font-weight: 900;">{{ page_speed }}/100</div>
                <p>Every second of load time reduces lead conversion by 17%.</p>
            </div>
        </div>

        <div class="cta-box">
            <h2 style="font-size: 2.5rem; margin-top: 0;">Claim Your Growth Map</h2>
            <p style="font-size: 1.1rem; margin-bottom: 30px; opacity: 0.9;">We have prepared a full architectural blueprint to recover the ${{ annual_leakage }}/yr leakage.</p>
            <a href="mailto:admin@nyxmar.com?subject=RE: {{ business_name }} Audit" class="cta-btn">ACTIVATE SOLUTIONS</a>
        </div>

        <div class="footer">
            Generated by RASER Intelligence Hub • Confidential & Proprietary
        </div>
    </div>
</body>
</html>
"""

def generate_diamond_report(lead_id):
    logger.info(f"Generating Diamond Report for: {lead_id}")
    # Fix: use fetch_leads with ID filter
    leads = db.fetch_leads(filters={"id": f"eq.{lead_id}"})
    if not leads:
        logger.error("Lead not found")
        return None
    lead = leads[0]

    url = lead.get('url')
    niche = lead.get('niche', 'Default')
    biz_name = lead.get('business_name', 'Your Business')
    domain = lead.get('domain', url)

    # 1. Audit Site
    audit = analyze_site(url)
    
    # 2. Calculate Leakage (Monthly -> Annual)
    monthly_leak = calculate_revenue_loss(niche, audit)
    annual_leak = monthly_leak * 12
    
    # 3. Generate AI Bullets
    try:
        ai_audit_text = generate_ai_audit(url, audit, niche)
        bullets = [b.strip().replace("* ", "").replace("- ", "") for b in ai_audit_text.split("\n") if b.strip()]
    except Exception as e:
        logger.warning(f"AI Audit failed for {biz_name}: {e}. Using high-stakes fallbacks.")
        bullets = []

    if len(bullets) < 2:
        if "Solar" in (niche or ""):
            bullets = [
                f"Mobile layout failures for {biz_name} are causing a 30%+ bounce rate among click-ready prospects.",
                f"Slow speed (under 40/100) is penalizing your Google Quality Score, increasing your lead cost.",
                f"Lack of conversion-optimized capture forms means 9 out of 10 visitors leave without a trace."
            ]
        elif "Attorney" in (niche or "") or "Injury" in (niche or ""):
            bullets = [
                f"Your site currently fails basic mobile trust tests, crucial for distressed prospects in your city.",
                f"Loading bottlenecks are handing your most expensive leads directly to your competitors.",
                f"Outdated UI elements are undermining your 'Premium' authority and reducing initial trust scores."
            ]
        else:
            bullets = [
                f"Technical debt is repelling high-value prospects and driving up your customer acquisition cost.",
                f"Your current digital presence lacks the 'Instant Connection' required for high-ticket conversions.",
                f"Infrastructure failures are making your digital funnel a cost center rather than a revenue engine."
            ]

    # 4. Render HTML
    tmpl = Template(DIAMOND_TEMPLATE)
    html = tmpl.render(
        business_name=biz_name,
        domain=domain,
        annual_leakage=f"{annual_leak:,}",
        mobile_friendly=audit.get('mobile_friendly', False),
        page_speed=audit.get('page_speed_score', 50),
        ai_bullets=bullets[:3]
    )

    # 5. Save
    folder = "diamond_reports"
    os.makedirs(folder, exist_ok=True)
    filename = f"{biz_name.lower().replace(' ', '-')}-audit.html"
    filepath = os.path.join(folder, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(html)
        
    logger.info(f"Diamond Report saved: {filepath}")
    return {
        "filepath": filepath,
        "annual_leakage": f"{annual_leak:,.0f}"
    }
