"""
reports_generator.py

Mini-report generator for Antigravity leads.

- Generates HTML summary report per lead (templated via Jinja2)
- Generates a basic PDF summary using ReportLab
- Saves files under ./reports/ (timestamped)
- Updates `signals` JSON in Supabase (adds report paths and links)
- Includes incremental batch runner to process only leads that don't already have a report
"""

import os
import json
import logging
import pathlib
from datetime import datetime
from typing import Optional

from jinja2 import Template
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle

from dotenv import load_dotenv

# Import from your existing pipeline
try:
    from antigravity_deal_score import LeadSignals, recommend_outreach_action
except Exception:
    LeadSignals = None

# Supabase client (for batch update)
try:
    from supabase import create_client
except Exception:
    create_client = None

load_dotenv()
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("reports_generator")

# Supabase config
SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
supabase = None
if create_client and SUPABASE_URL and SUPABASE_KEY:
    try:
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
    except Exception as e:
        logger.warning(f"Supabase initialization failed in reports_generator: {e}")
else:
    logger.info("Supabase client not configured. DB updates will be skipped.")

# Report folder
REPORT_DIR = pathlib.Path("reports")
REPORT_DIR.mkdir(exist_ok=True)

# HTML template (Jinja2)
HTML_TEMPLATE = Template("""
<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>AI Audit — {{ domain }}</title>
  <style>
    body{font-family: Inter, Arial, sans-serif; background:#f7fafc; color:#111; padding:30px;}
    .card{max-width:900px;margin:0 auto;background:#fff;padding:24px;border-radius:12px;box-shadow:0 10px 30px rgba(2,6,23,0.08);}
    h1{margin:0 0 8px;font-size:24px}
    .meta{color:#6b7280;font-size:13px;margin-bottom:12px}
    .kpi{display:flex; gap:12px; flex-wrap:wrap; margin:10px 0}
    .kpi .item{background:#f1f5f9;padding:10px;border-radius:8px;min-width:140px}
    pre{background:#0f172a;color:#e2e8f0;padding:12px;border-radius:8px;overflow:auto}
    footer{font-size:13px;color:#6b7280;margin-top:14px}
    a.cta{display:inline-block;margin-top:12px;padding:8px 12px;background:#0066ff;color:#fff;border-radius:8px;text-decoration:none}
  </style>
</head>
<body>
  <div class="card">
    <h1>AI Audit for {{ domain }}</h1>
    <div class="meta">Generated: {{ timestamp }} — Deal Score: <strong>{{ deal_score }}</strong> — Action: <strong>{{ action }}</strong></div>

    <div class="kpi">
      <div class="item"><strong>Load (s)</strong><div>{{ slow_load_estimate or 'N/A' }}</div></div>
      <div class="item"><strong>SERP rank</strong><div>{{ serp_rank or 'N/A' }}</div></div>
      <div class="item"><strong>Mobile responsive</strong><div>{{ 'Yes' if has_viewport_meta else 'No' }}</div></div>
      <div class="item"><strong>Multiple locations</strong><div>{{ multiple_locations }}</div></div>
    </div>

    <h3>Key signals</h3>
    <pre>{{ signals_json }}</pre>

    <h3>Short pitch (copy)</h3>
    <pre>
Hi {{ domain }},
We ran a quick audit and estimate your website is losing potential revenue. Key issues: {{ issues_summary }}.
We created a demo preview and a short plan — view the report or reply to book a 15-minute call.
    </pre>

    <a class="cta" href="{{ preview_link }}">View live preview</a>
    <footer>Generated by Antigravity • Do not share publicly without permission</footer>
  </div>
</body>
</html>
""")

def _safe_filename(prefix: str, domain: str, ext: str = "html") -> str:
    ts = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    safe = "".join(ch if ch.isalnum() or ch in ("-", "_") else "-" for ch in domain)
    return f"{prefix}_{safe}_{ts}.{ext}"

def generate_report_html(signals: "LeadSignals") -> str:
    """Render HTML string for a lead."""
    issues = []
    if getattr(signals, "slow_load_estimate", None) and signals.slow_load_estimate > 4:
        issues.append(f"Slow load ({signals.slow_load_estimate}s)")
    if getattr(signals, "missing_schema", False):
        issues.append("Missing schema.org markup")
    if getattr(signals, "outdated_theme_hint", False):
        issues.append("Outdated design")
    if getattr(signals, "serp_rank", None) and signals.serp_rank > 10:
        issues.append(f"Low search ranking (#{signals.serp_rank})")
    if not issues:
        issues_summary = "Minor technical & UX improvements"
    else:
        issues_summary = "; ".join(issues)

    preview_link = "#"
    if signals.raw and signals.raw.get("digital_twin_path"):
        preview_link = signals.raw.get("digital_twin_path")

    raw_data = {}
    if signals and hasattr(signals, 'raw'):
        raw_data = signals.raw or {}
    
    html = HTML_TEMPLATE.render(
        domain=getattr(signals, 'domain', 'Unknown') if signals else 'Unknown',
        timestamp=datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        deal_score=getattr(signals, 'deal_score', 0) if signals else 0,
        action=recommend_outreach_action(signals) if signals else 'ignore',
        slow_load_estimate=getattr(signals, "slow_load_estimate", None),
        serp_rank=getattr(signals, "serp_rank", None),
        has_viewport_meta=getattr(signals, "has_viewport_meta", False),
        multiple_locations=getattr(signals, "multiple_locations", 0),
        signals_json=json.dumps(raw_data or asdict_safe(signals), indent=2),
        issues_summary=issues_summary,
        preview_link=preview_link,
    )
    return html

def asdict_safe(signals):
    """Fallback if dataclass conversion is needed."""
    try:
        from dataclasses import asdict
        return asdict(signals)
    except Exception:
        return signals.__dict__

def save_report_html(signals: "LeadSignals") -> str:
    """Save HTML report to REPORT_DIR and return path."""
    filename = _safe_filename("report", signals.domain, "html")
    path = REPORT_DIR / filename
    html = generate_report_html(signals)
    path.write_text(html, encoding="utf-8")
    logger.info(f"Saved HTML report: {path}")
    return str(path)

def generate_pdf_report(signals: "LeadSignals", pdf_path: str) -> bool:
    """
    Create a simple PDF summary using ReportLab.
    Returns True on success.
    """
    try:
        doc = SimpleDocTemplate(pdf_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()
        styleH = styles["Heading1"]
        styleN = styles["BodyText"]
        elems = []

        elems.append(Paragraph(f"AI Audit — {signals.domain}", styleH))
        elems.append(Spacer(1, 8))
        elems.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", styleN))
        elems.append(Spacer(1, 12))

        # Key table
        data = [
            ["Deal Score", str(getattr(signals, 'deal_score', 0))],
            ["Recommended Action", recommend_outreach_action(signals) if signals else 'ignore'],
            ["Load (s)", str(getattr(signals, "slow_load_estimate", "N/A"))],
            ["SERP rank", str(getattr(signals, "serp_rank", "N/A"))],
            ["Mobile responsive", "Yes" if getattr(signals, "has_viewport_meta", False) else "No"],
            ["Multiple locations", str(getattr(signals, "multiple_locations", 0))],
        ]
        table = Table(data, colWidths=[200, 300])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ]))
        elems.append(table)
        elems.append(Spacer(1, 12))

        elems.append(Paragraph("Quick Signals & Notes:", styles["Heading3"]))
        raw_json = json.dumps(signals.raw or asdict_safe(signals), indent=2)
        # For PDF readability, split raw_json into paragraphs of reasonable length
        for chunk in split_text(raw_json, 800):
            elems.append(Paragraph(f" {chunk} ", styleN))
            elems.append(Spacer(1, 6))

        doc.build(elems)
        logger.info(f"Generated PDF report: {pdf_path}")
        return True
    except Exception as e:
        logger.warning(f"PDF generation failed for {signals.domain}: {e}")
        return False

def split_text(text: str, size: int = 800):
    """Split long text into pieces for PDF paragraphs."""
    return [text[i:i+size] for i in range(0, len(text), size)]

def save_mini_report(signals: "LeadSignals", make_pdf: bool = True, push_to_db: bool = True) -> dict:
    """
    Create HTML (and optionally PDF) reports for a lead, store paths in signals.raw,
    and optionally push updated signals JSON to Supabase.
    Returns a dict with file paths.
    """
    out = {}
    if signals is None:
        return out

    html_path = save_report_html(signals)
    out["html_path"] = html_path
    
    current_raw = getattr(signals, 'raw', {}) or {}
    current_raw["report_html_path"] = html_path
    current_raw["report_preview_link"] = f"[View Report]({html_path})"
    if hasattr(signals, 'raw'):
        signals.raw = current_raw

    if make_pdf:
        pdf_filename = _safe_filename("report", signals.domain, "pdf")
        pdf_path = str(REPORT_DIR / pdf_filename)
        ok = generate_pdf_report(signals, pdf_path)
        if ok and hasattr(signals, 'raw') and signals.raw is not None:
            out["pdf_path"] = pdf_path
            signals.raw["report_pdf_path"] = pdf_path
            signals.raw["report_pdf_link"] = f"[Download PDF]({pdf_path})"

    # push to supabase signals column (if supabase available)
    if push_to_db and supabase and signals:
        try:
            domain_val = getattr(signals, 'domain', None)
            if domain_val:
                supabase.table("leads").update({"signals": json.dumps(asdict_safe(signals))}).eq("domain", domain_val).execute()
                logger.info(f"Pushed updated signals for {domain_val} to Supabase")
        except Exception as e:
            logger.warning(f"Failed to push report paths to Supabase: {e}")

    return out

# ---------------------------
# Batch incremental runner
# ---------------------------

def fetch_new_leads_missing_reports(limit: int = 1000):
    """
    Fetch leads from Supabase that don't have report_pdf_path (or pdf missing).
    Returns list of parsed signals dicts.
    """
    if not supabase:
        raise RuntimeError("Supabase not configured; cannot fetch leads.")
    resp = supabase.table("leads").select("*").execute()
    rows = resp.data if hasattr(resp, 'data') else (resp.get("data", []) if isinstance(resp, dict) else [])
    candidates = []
    for r in rows:
        try:
            signals_json = r.get("signals", {})
            if isinstance(signals_json, str):
                signals_dict = json.loads(signals_json)
            else:
                signals_dict = signals_json or {}
            
            raw = signals_dict.get("raw") or {}
            if raw and raw.get("report_pdf_path"):
                continue
            
            if LeadSignals:
                # Ensure we only pass keys that exist in LeadSignals dataclass
                import dataclasses
                field_names = {f.name for f in dataclasses.fields(LeadSignals)}
                filtered_signals = {k: v for k, v in signals_dict.items() if k in field_names}
                lead = LeadSignals(**filtered_signals)
            else:
                lead = signals_dict
            candidates.append(lead)
            if len(candidates) >= limit:
                break
        except Exception as e:
            logger.warning(f"Skipping row parsing error for {r.get('domain')}: {e}")
    return candidates

def generate_reports_incremental(limit: int = 200):
    try:
        leads = fetch_new_leads_missing_reports(limit=limit)
    except Exception as e:
        logger.error(f"Failed to fetch leads: {e}")
        return

    logger.info(f"Found {len(leads)} leads missing reports")
    created = 0
    for lead in leads:
        try:
            # Only create reports for high-value action
            action = recommend_outreach_action(lead)
            if action != "digital_twin_revenue_simulation":
                continue
            save_mini_report(lead, make_pdf=True, push_to_db=True)
            created += 1
        except Exception as e:
            logger.warning(f"Failed to generate report for {getattr(lead,'domain', 'unknown')}: {e}")
    logger.info(f"Created {created} new reports")

# If run directly
if __name__ == "__main__":
    generate_reports_incremental()
